### ISSUE TITLE
Nodes don't mirror when dragged to other side of root

### ISSUE THREAD

**Issue by CapinWinky** [jiangxin/freemind-mmx#2]
I know this is probably a long dead project, but I still use Freemind and also git and really disliked how it would have differences that didn't matter to the content of the file. I've just started using your version, but I can't find a way to move a node from one side of the root to the other and have it mirror so the line comes out of the correct side. I have to open the `.mm` file and manually change the position from `right` to `left`, then reposition it in the GUI.

I don't know if the original project had this issue or if it is new in this fork. I seem to recall the original had a bug where a node would mirror, but its children wouldn't.

EDIT: Nevermind, CTRL+Arrow left/right works fine.

**Comment by jiangxin** [comment]
I use [freeplane](https://www.freeplane.org/wiki/index.php/Home) which works better on macOS.
